project:
  type: book

book:
  title: "CircuitPython for Biomakers"
  author: "Biomaker Team, University of Cambridge"
  date: "12/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt




