project:
  type: book

book:
  title: "CircuitPython for Biomakers"
  author: "Biomaker Team, University of Cambridge"
  date: "12/12/2025"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - starter_kit.qmd
        - circuitpython_datatypes.qmd
    - part: lesson2.qmd
      chapters: 
        - setting_up_board.qmd
        - testing_board.qmd
        - testing_sensor_kit_base.qmd
        - io_devices.qmd
    - part: lesson3.qmd
    - part: lesson4.qmd
    - part: lesson5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-copy: true 
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt




