# Testing your board {.unnumbered}

## Serial output
A new installation of CircuitPython provides the following sample program (code.py):
```
print("Hello World!")
```

Open the serial monitor in VS Code and you should see the following output:

> code.py output:

> Hello World!

> Code done running.

> Press any key to enter the REPL. Use CTRL-D to reload.


You may need to send CTRL-D to reload.


## Flash onboard LED

<https://github.com/WaylandM/Biomaker-CircuitPython/blob/main/examples/flash_onboard_led/code.py>

Content of code.py:
```python
import time
import board
import digitalio

led = digitalio.DigitalInOut(board.LED)
led.direction = digitalio.Direction.OUTPUT

while True:
    led.value = True   # LED on
    time.sleep(0.5)
    led.value = False  # LED off
    time.sleep(0.5)
```


This script will:

1. Set up the onboard LED pin as a digital output.
2. Turn in on for 0.5 seconds.
3. Turn it off for 0.5 seconds.
4. Repeat this on-off cycle indefinitely.



Let’s go through the example line by line and explain what each part does.

```python
import time
import board
import digitalio
```

* `time` gives access to timing functions like `sleep()`.
* `board` contains names for the physical pins on your specific board (like `board.LED`).
* `digitalio` lets you control pins as simple on/off digital signals.

```python
led = digitalio.DigitalInOut(board.LED)
```

* `board.LED` is a predefined pin that’s connected to the onboard LED.
* `DigitalInOut(...)` creates an object that lets you control that pin.
* The variable `led` now represents the LED pin.

```python
led.direction = digitalio.Direction.OUTPUT
```

* Pins can be inputs (read signals) or outputs (send signals).
* Here we set the LED pin to be an **output**, so we can drive it on and off.

```python
while True:
```

* This starts an infinite loop.
* Everything indented underneath will repeat forever until the board is reset or powered off.

```python
    led.value = True   # LED on
```

* Setting `value` to `True` sends a HIGH signal to the pin.
* On most boards this turns the LED on.

```python
    time.sleep(0.5)
```

* Pause the program for 0.5 seconds (500 milliseconds).
* The LED stays on during this pause.

```python
    led.value = False  # LED off
```

* Setting `value` to `False` sends a LOW signal.
* This turns the LED off.

```python
    time.sleep(0.5)
```

* Wait another 0.5 seconds with the LED off.
* Then the loop repeats, so the LED turns on again.

Overall behaviour:

1. Turn LED on
2. Wait half a second
3. Turn LED off
4. Wait half a second
5. Repeat forever

That creates a steady blink: on–off–on–off every second.



## Flash onboard NeoPixel

<https://github.com/WaylandM/Biomaker-CircuitPython/tree/main/examples/flash_onboard_neopixel_led>

Content of code.py:

```python
import time
import board
import neopixel

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

while True:
    pixel[0] = (50, 0, 0)  # red
    time.sleep(0.5)
    pixel[0] = (0, 0, 0)   # off
    time.sleep(0.5)

```

Line by line explanation:

```python
pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)
```

* Creates a NeoPixel controller on the pin connected to the onboard RGB LED.
* `1` means there is one pixel.

```python
pixel[0] = (50, 0, 0)
```

* Sets pixel 0 to a colour using RGB values.
* `(50, 0, 0)` = red (brightness 50 out of 255).

```python
pixel[0] = (0, 0, 0)
```

* Sets the pixel to black (all channels 0) = off.

The same infinite loop and `time.sleep(0.5)` calls make it blink on and off.

In both cases, you’re just repeatedly:

* writing a value to the LED
* waiting a bit
* writing the opposite value
* waiting again


Download project bundle
